apiVersion: v1
kind: Secret
metadata:
  name: hcm-db
type: Opaque
data:
  url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnJaenF9SE5mSFFlOU5sP25SUTYyQGhjbS1kYi5jdG1pMGVtY3U3MWYuZXUtY2VudHJhbC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvaGNt   # "postgres" base64
